# Generated by Django 4.1.4 on 2023-06-12 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GeeksModel",
            new_name="DataModel",
        ),
    ]
